package br.ufrgs.inf.gar.snmp.manager.ui.tab.aptos;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

@SuppressWarnings("serial")
public class AptosLayout extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	public AptosLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Apartamentos");
	}

	@AutoGenerated
	private void buildMainLayout() {
		mainLayout = new AbsoluteLayout();
	}

	public AbsoluteLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(AbsoluteLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

}
