package br.ufrgs.inf.gar.cwm.ui.tab.condo;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class CondoInfoLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout baseLayout;
	@AutoGenerated
	private Table tableInfo;
	
	public CondoInfoLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Condomínio");
		baseLayout.setMargin(new MarginInfo(true, true, true, false));
		tableInfo.setStyleName(ValoTheme.TABLE_SMALL);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// baseLayout
		baseLayout = buildBaseLayout();
		mainLayout.addComponent(baseLayout, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBaseLayout() {
		// common part: create layout
		baseLayout = new VerticalLayout();
		baseLayout.setImmediate(false);
		baseLayout.setWidth("-1px");
		baseLayout.setHeight("-1px");
		
		// tableInfo
		tableInfo = new Table();
		tableInfo.setImmediate(false);
		tableInfo.setWidth("362px");
		tableInfo.setHeight("322px");
		baseLayout.addComponent(tableInfo);
		baseLayout.setExpandRatio(tableInfo, 0.1f);
		
		return baseLayout;
	}

	public Table getTableInfo() {
		return tableInfo;
	}

	public void setTableInfo(Table tableInfo) {
		this.tableInfo = tableInfo;
	}

}
