package br.ufrgs.inf.gar.condominium.manager.ui.tab.apartment;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class AptStatsLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout baseLayout;
	@AutoGenerated
	private Panel chartPanel;
	@AutoGenerated
	private VerticalLayout chartPanelLayout;
	
	public AptStatsLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Apartamentos");
		baseLayout.setMargin(new MarginInfo(true, true, true, false));
	}

	public VerticalLayout getBaseLayout() {
		return baseLayout;
	}

	public VerticalLayout getChartPanelLayout() {
		return chartPanelLayout;
	}

	public void setChartPanelLayout(VerticalLayout chartPanelLayout) {
		this.chartPanelLayout = chartPanelLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// baseLayout
		baseLayout = buildBaseLayout();
		mainLayout.addComponent(baseLayout,
				"top:0.0px;right:-2.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBaseLayout() {
		// common part: create layout
		baseLayout = new VerticalLayout();
		baseLayout.setImmediate(false);
		baseLayout.setWidth("100.0%");
		baseLayout.setHeight("100.0%");
		baseLayout.setMargin(false);
		
		// chartPanel
		chartPanel = buildChartPanel();
		baseLayout.addComponent(chartPanel);
		
		return baseLayout;
	}

	@AutoGenerated
	private Panel buildChartPanel() {
		// common part: create layout
		chartPanel = new Panel();
		chartPanel.setImmediate(false);
		chartPanel.setWidth("-1px");
		chartPanel.setHeight("-1px");
		
		// chartPanelLayout
		chartPanelLayout = new VerticalLayout();
		chartPanelLayout.setImmediate(false);
		chartPanelLayout.setWidth("100.0%");
		chartPanelLayout.setHeight("100.0%");
		chartPanelLayout.setMargin(false);
		chartPanel.setContent(chartPanelLayout);
		
		return chartPanel;
	}

}
