package br.ufrgs.inf.gar.snmp.manager.ui.tab.home;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class HomeLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout baseLayout;
	@AutoGenerated
	private HorizontalLayout inputLayout;
	@AutoGenerated
	private Button oidButton;
	@AutoGenerated
	private TextField oidField;
	
	public HomeLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Home");
		oidButton.setCaption("Get");
		oidField.setCaption("Digite o OID");
	}

	public Button getOidButton() {
		return oidButton;
	}

	public void setOidButton(Button oidButton) {
		this.oidButton = oidButton;
	}

	public TextField getOidField() {
		return oidField;
	}

	public void setOidField(TextField oidField) {
		this.oidField = oidField;
	}

	public VerticalLayout getBaseLayout() {
		return baseLayout;
	}

	public void setBaseLayout(VerticalLayout baseLayout) {
		this.baseLayout = baseLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// baseLayout
		baseLayout = buildBaseLayout();
		mainLayout.addComponent(baseLayout, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBaseLayout() {
		// common part: create layout
		baseLayout = new VerticalLayout();
		baseLayout.setImmediate(false);
		baseLayout.setWidth("100.0%");
		baseLayout.setHeight("100.0%");
		baseLayout.setMargin(true);
		
		// inputLayout
		inputLayout = buildInputLayout();
		baseLayout.addComponent(inputLayout);
		
		return baseLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildInputLayout() {
		// common part: create layout
		inputLayout = new HorizontalLayout();
		inputLayout.setImmediate(false);
		inputLayout.setWidth("-1px");
		inputLayout.setHeight("-1px");
		inputLayout.setMargin(false);
		inputLayout.setSpacing(true);
		
		// oidField
		oidField = new TextField();
		oidField.setCaption("Digite o OID");
		oidField.setImmediate(false);
		oidField.setWidth("206px");
		oidField.setHeight("-1px");
		inputLayout.addComponent(oidField);
		inputLayout.setComponentAlignment(oidField, new Alignment(10));
		
		// oidButton
		oidButton = new Button();
		oidButton.setCaption("Button");
		oidButton.setImmediate(true);
		oidButton.setWidth("-1px");
		oidButton.setHeight("-1px");
		inputLayout.addComponent(oidButton);
		inputLayout.setComponentAlignment(oidButton, new Alignment(10));
		
		return inputLayout;
	}

}
