package br.ufrgs.inf.gar.snmp.condominium.manager.ui.tab.condominium;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

@SuppressWarnings("serial")
public class CondominiumInfoLayout extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	public CondominiumInfoLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Condomínio");
	}

	@AutoGenerated
	private void buildMainLayout() {
		mainLayout = new AbsoluteLayout();
	}

}
