package br.ufrgs.inf.gar.snmp.manager.ui.tab.condominium;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class CondominiumLightLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout baseLayout;
	@AutoGenerated
	private Panel livePanel;
	@AutoGenerated
	private VerticalLayout livePanelLayout;
	
	public CondominiumLightLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Eletricidade");
		baseLayout.setMargin(new MarginInfo(true, true, true, false));
	}

	public HorizontalLayout getBaseLayout() {
		return baseLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// baseLayout
		baseLayout = buildBaseLayout();
		mainLayout.addComponent(baseLayout, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildBaseLayout() {
		// common part: create layout
		baseLayout = new HorizontalLayout();
		baseLayout.setImmediate(false);
		baseLayout.setWidth("100.0%");
		baseLayout.setHeight("100.0%");
		baseLayout.setMargin(false);
		
		// livePanel
		livePanel = buildLivePanel();
		baseLayout.addComponent(livePanel);
		
		return baseLayout;
	}

	@AutoGenerated
	private Panel buildLivePanel() {
		// common part: create layout
		livePanel = new Panel();
		livePanel.setImmediate(false);
		livePanel.setWidth("-1px");
		livePanel.setHeight("-1px");
		
		// livePanelLayout
		livePanelLayout = new VerticalLayout();
		livePanelLayout.setImmediate(false);
		livePanelLayout.setWidth("100.0%");
		livePanelLayout.setHeight("100.0%");
		livePanelLayout.setMargin(false);
		livePanel.setContent(livePanelLayout);
		
		return livePanel;
	}

	public VerticalLayout getLivePanelLayout() {
		return livePanelLayout;
	}

	public void setLivePanelLayout(VerticalLayout livePanelLayout) {
		this.livePanelLayout = livePanelLayout;
	}
}
