package br.ufrgs.inf.gar.snmp.manager.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Sizeable;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class ManagerLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel splitPanel;
	@AutoGenerated
	private VerticalLayout content;
	@AutoGenerated
	private TabSheet tabs;
	@AutoGenerated
	private VerticalLayout menu;
	@AutoGenerated
	private Button aptosButton;
	@AutoGenerated
	private Button generalButton;
	@AutoGenerated
	private Button homeButton;
	@AutoGenerated
	private HorizontalLayout top;
	@AutoGenerated
	private Label titleLabel;
	
	public ManagerLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		splitPanel.setSplitPosition(20, Sizeable.Unit.PERCENTAGE);
		titleLabel.setValue("SNMP Manager");
		titleLabel.addStyleName("label-title");
		aptosButton.setCaption("Apartamentos");
		generalButton.setCaption("Condominio");
		homeButton.setCaption("Home");
	}

	public TabSheet getTabs() {
		return tabs;
	}

	public void setTabs(TabSheet tabs) {
		this.tabs = tabs;
	}

	public Button getAptosButton() {
		return aptosButton;
	}

	public void setAptosButton(Button aptosButton) {
		this.aptosButton = aptosButton;
	}

	public Button getGeneralButton() {
		return generalButton;
	}

	public void setGeneralButton(Button generalButton) {
		this.generalButton = generalButton;
	}

	public Button getHomeButton() {
		return homeButton;
	}

	public void setHomeButton(Button homeButton) {
		this.homeButton = homeButton;
	}

	public Button getCondominiumButton() {
		return generalButton;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// top
		top = buildTop();
		mainLayout.addComponent(top, "top:0.0px;left:0.0px;");
		
		// splitPanel
		splitPanel = buildSplitPanel();
		mainLayout.addComponent(splitPanel, "top:80.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildTop() {
		// common part: create layout
		top = new HorizontalLayout();
		top.setImmediate(false);
		top.setWidth("100.0%");
		top.setHeight("100px");
		top.setMargin(false);
		
		// titleLabel
		titleLabel = new Label();
		titleLabel.setImmediate(false);
		titleLabel.setWidth("-1px");
		titleLabel.setHeight("-1px");
		titleLabel.setValue("Label");
		top.addComponent(titleLabel);
		top.setComponentAlignment(titleLabel, new Alignment(48));
		
		return top;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildSplitPanel() {
		// common part: create layout
		splitPanel = new HorizontalSplitPanel();
		splitPanel.setImmediate(false);
		splitPanel.setWidth("100.0%");
		splitPanel.setHeight("100.0%");
		
		// menu
		menu = buildMenu();
		splitPanel.addComponent(menu);
		
		// content
		content = buildContent();
		splitPanel.addComponent(content);
		
		return splitPanel;
	}

	@AutoGenerated
	private VerticalLayout buildMenu() {
		// common part: create layout
		menu = new VerticalLayout();
		menu.setImmediate(false);
		menu.setWidth("100.0%");
		menu.setHeight("-1px");
		menu.setMargin(true);
		
		// homeButton
		homeButton = new Button();
		homeButton.setCaption("Button");
		homeButton.setImmediate(true);
		homeButton.setWidth("100.0%");
		homeButton.setHeight("-1px");
		menu.addComponent(homeButton);
		
		// generalButton
		generalButton = new Button();
		generalButton.setCaption("Button");
		generalButton.setImmediate(true);
		generalButton.setWidth("100.0%");
		generalButton.setHeight("-1px");
		menu.addComponent(generalButton);
		
		// aptosButton
		aptosButton = new Button();
		aptosButton.setCaption("Button");
		aptosButton.setImmediate(true);
		aptosButton.setWidth("100.0%");
		aptosButton.setHeight("-1px");
		menu.addComponent(aptosButton);
		
		return menu;
	}

	@AutoGenerated
	private VerticalLayout buildContent() {
		// common part: create layout
		content = new VerticalLayout();
		content.setImmediate(false);
		content.setWidth("100.0%");
		content.setHeight("1000px");
		content.setMargin(true);
		
		// tabs
		tabs = new TabSheet();
		tabs.setImmediate(false);
		tabs.setWidth("100.0%");
		tabs.setHeight("1000px");
		content.addComponent(tabs);
		content.setExpandRatio(tabs, 1.0f);
		
		return content;
	}

}
