package br.ufrgs.inf.gar.condominium.manager.ui.tab.home;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class HomeLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout baseLayout;
	@AutoGenerated
	private Label responseLabel;
	@AutoGenerated
	private VerticalLayout oidFormLayout;
	@AutoGenerated
	private HorizontalLayout oidInputLayout;
	@AutoGenerated
	private Button oidButton;
	@AutoGenerated
	private TextField oidField;
	public HomeLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setCaption("Home");
		oidButton.setCaption("Get");
		oidField.setCaption("Digite o OID");
		baseLayout.setMargin(new MarginInfo(true, true, true, false));
	}

	public Button getOidButton() {
		return oidButton;
	}

	public void setOidButton(Button oidButton) {
		this.oidButton = oidButton;
	}

	public TextField getOidField() {
		return oidField;
	}

	public void setOidField(TextField oidField) {
		this.oidField = oidField;
	}

	public VerticalLayout getBaseLayout() {
		return baseLayout;
	}

	public void setBaseLayout(VerticalLayout baseLayout) {
		this.baseLayout = baseLayout;
	}

	public Label getResponseLabel() {
		return responseLabel;
	}

	public void setResponseLabel(Label responseLabel) {
		this.responseLabel = responseLabel;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// baseLayout
		baseLayout = buildBaseLayout();
		mainLayout.addComponent(baseLayout, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBaseLayout() {
		// common part: create layout
		baseLayout = new VerticalLayout();
		baseLayout.setImmediate(false);
		baseLayout.setWidth("-1px");
		baseLayout.setHeight("-1px");
		baseLayout.setMargin(true);
		
		// oidFormLayout
		oidFormLayout = buildOidFormLayout();
		baseLayout.addComponent(oidFormLayout);
		
		// responseLabel
		responseLabel = new Label();
		responseLabel.setImmediate(false);
		responseLabel.setWidth("-1px");
		responseLabel.setHeight("-1px");
		responseLabel.setValue("Label");
		baseLayout.addComponent(responseLabel);
		
		return baseLayout;
	}

	@AutoGenerated
	private VerticalLayout buildOidFormLayout() {
		// common part: create layout
		oidFormLayout = new VerticalLayout();
		oidFormLayout.setImmediate(false);
		oidFormLayout.setWidth("-1px");
		oidFormLayout.setHeight("-1px");
		oidFormLayout.setMargin(false);
		
		// oidInputLayout
		oidInputLayout = buildOidInputLayout();
		oidFormLayout.addComponent(oidInputLayout);
		
		return oidFormLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildOidInputLayout() {
		// common part: create layout
		oidInputLayout = new HorizontalLayout();
		oidInputLayout.setImmediate(false);
		oidInputLayout.setWidth("-1px");
		oidInputLayout.setHeight("-1px");
		oidInputLayout.setMargin(false);
		oidInputLayout.setSpacing(true);
		
		// oidField
		oidField = new TextField();
		oidField.setCaption("Digite o OID");
		oidField.setImmediate(false);
		oidField.setWidth("206px");
		oidField.setHeight("-1px");
		oidInputLayout.addComponent(oidField);
		
		// oidButton
		oidButton = new Button();
		oidButton.setCaption("Button");
		oidButton.setImmediate(true);
		oidButton.setWidth("-1px");
		oidButton.setHeight("-1px");
		oidInputLayout.addComponent(oidButton);
		oidInputLayout.setComponentAlignment(oidButton, new Alignment(10));
		
		return oidInputLayout;
	}

}
